Neos:
  Neos:
    fusion:
      autoInclude:
        'Dotpulse.MediaRow': TRUE

    userInterface:
      translation:
        autoInclude:
          'Dotpulse.MediaRow': ['NodeTypes/*']

Dotpulse:
  MediaRow:
    baseWith: 1440
    includeCSS: FALSE
    class:
      container: container
      row: dotpulse-mediarow--row
      col: dotpulse-mediarow--col
